### ISSUE TITLE
COSMOS Dev Thread

### ISSUE THREAD

**Issue by hemmer** [BlackNoiseModular/VCV#1]
Core/DSP
- [x] Implement core logic outputs
- [x] Implement gates/triggers for logic outputs
  - [x] Decide on Schmitt Trigger vs direct comparator versions
- [x] Optional oversampling for relevant outputs
  - [x] Context menu to turn oversampling on/off

UI
- [x] Build module with placeholder graphics
- [x] Update to production graphics
- [x] Implement touch pad (slew, variable voltage)
- [x] Other cosmetic (e.g. descriptions for ports)

**Comment by hemmer** [comment]
Ignoring gate/trigger outputs to start with, I'd like to better understand the XOR gate. In particular I think it has a "special case" behaviour at X or Y = 0. Here I have sin into X and DC into Y. Positive Y DC inverts and clips, negative Y just clips. Naively I had thought that as Y goes to 0 (from positive side or negative side), the clipping window gets narrower and narrower until XOR output is 0 (when say Y = 0). But in fact, Y = 0 (end of the video) is a special case that lets the original wavform through as far as I know. 

https://github.com/BlackNoiseModular/VCV/assets/915048/780f21f2-9f6a-4a47-8e4f-38ae41899c8e

The way this manifests (at least in the manual) is that Y = 0 lets X through unchanged (see cyan bits). But if this is the case then why don't you get spikes (of the pure X signal) as Y (purple) passes through zero in example 3)? 

![image](https://github.com/BlackNoiseModular/VCV/assets/915048/153ca8ef-4ed1-4906-96af-005a09cad821)

For the record, this is how I've implemented it to start with in VCV but just checking that this is the expected behvaiour?
![image](https://github.com/BlackNoiseModular/VCV/assets/915048/6b3345c5-da82-4b36-b316-356c04dc6aa6)

**Comment by BlackNoiseModular** [comment]
Indeed, that's an error in the manual that we hadn't noticed. The illustration should not be labeled with "gates" because it depicts bipolar signals. The "TZ Clipper" and "Inv Tz Clipper" sections require at least one of the two inputs (X or Y) to be bipolar to function. However, this does not affect  the gate and trig outputs of those sections. So, if you send gate signals to both X and Y inputs, the "TZ Clipper" output will behave like the "INV MIN" output, and the gate output will behave like an XOR operation.

**Comment by hemmer** [comment]
> Indeed, that's an error in the manual that we hadn't noticed. The illustration should not be labeled with "gates" because it depicts bipolar signals. The "TZ Clipper" and "Inv Tz Clipper" sections require at least one of the two inputs (X or Y) to be bipolar to function. However, this does not affect the gate and trig outputs of those sections. So, if you send gate signals to both X and Y inputs, the "TZ Clipper" output will behave like the "INV MIN" output, and the gate output will behave like an XOR operation.

Great thanks for the clarification, and with that understanding I now get the same behaviour at "TZ Clipper" output as "INV MIN" output. However, sending the same gate pattern in (where say gate high is 10V), then I the green trace (oscillating from -10 to 0V), which is what I expect. 

![image](https://github.com/BlackNoiseModular/VCV/assets/915048/f79dd661-20ed-4cd1-8fab-0b667cc2ec94)

However this never exceeds 0V and so never triggers a gate (at least according to my literal interpretation of the manual)?

![image](https://github.com/BlackNoiseModular/VCV/assets/915048/f27f45ef-fcd0-490c-b98f-b27401502cc4)

**Comment by BlackNoiseModular** [comment]
To have the gate output behave like an XOR even with unipolar signals (e.g. gates) the Gate/Trigger section of the TZ Clipper and Inv-TZ Clipper is a bit different from the other sections. Instead of sending the TZ Clipper output to a comparator that generates all the gates/triggers, the X and Y inputs are sent into a logical XOR. This allows to generate gates even with unipolar signals. The XOR output is then sent into the comparator, which creates the gates and triggers for the TZ/Inv-TZ clipper sections.

**Comment by hemmer** [comment]
@BlackNoiseModular - you might have already seen, but I have build-on-push set up here https://github.com/BlackNoiseModular/VCV/releases. If you add to the plugins folder your user folder in Rack you should be able to try it out as we go. I'm on M1 mac so use the BlackNoiseModular-2.0.0-mac-arm64.vcvplugin file (this gets auto-extracted on startup).

Still plenty to do for all modules, but it'd be good if you can take a look at the logic outputs and their gate equivelents of COSMOS, and tell me if that is what you expect? Lower hemisphere outputs are literal inverses of top hemisphere, and all gate outs should follow the truth table on pg 15 of the manual. Triggers should coincide with rising edge of all matching gate outputs.

![image](https://github.com/user-attachments/assets/6475851f-b98b-406f-bf0c-276b0f9bb580)

Once you're happy with functional behaviour, I can implement oversampling etc. :)

**Comment by hemmer** [comment]
![Screenshot 2024-07-15 at 07 45 01](https://github.com/user-attachments/assets/97a1b6d9-47b0-4fe0-8ba9-4880ca68309b)

>  I took a photo to show the behavior of the "analog XOR" output and the "logic XOR" output. The green sine wave goes into the X input, and the blue DC voltage goes into the Y input. At the "analog XOR" output, the DC signal clips the sine wave (in red), but the "logic XOR" (in yellow) output works in a "bipolar" manner




I have to admit I'm a bit confused by this example you shared though? Sine to X, negative DC to Y, I get the clipped sine (red) as you do, but based on the manual pg 10 I would expect gate high (yellow) whenever red trace is greater than 0 (as below)? Instead it reminds me of the window comparator patch. (_traces slightly offset for clarity_)

![image](https://github.com/user-attachments/assets/5ca2bc21-4be0-429c-b5fb-e41fc879b042)

**Comment by BlackNoiseModular** [comment]
> ![Screenshot 2024-07-15 at 07 45 01](https://private-user-images.githubusercontent.com/915048/348617786-97a1b6d9-47b0-4fe0-8ba9-4880ca68309b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjc3MzIsIm5iZiI6MTcyMTAyNzQzMiwicGF0aCI6Ii85MTUwNDgvMzQ4NjE3Nzg2LTk3YTFiNmQ5LTQ3YjAtNGZlMC04YmE5LTQ4ODBjYTY4MzA5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNzEwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDY0NDUwMTU3YzM2MmVjNzE0NThkMGNhNTNmYzNmZjY4Y2Y5NDE4YmJhNzFkNmRiYjBiMzhjZGNmMzg5NDA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6r-8-XQu_2F_aL4JNVO0XcNGnYYPkM6wWCctAHA45PE)
> 
> > I took a photo to show the behavior of the "analog XOR" output and the "logic XOR" output. The green sine wave goes into the X input, and the blue DC voltage goes into the Y input. At the "analog XOR" output, the DC signal clips the sine wave (in red), but the "logic XOR" (in yellow) output works in a "bipolar" manner
> 
> I have to admit I'm a bit confused by this example you shared though? Sine to X, negative DC to Y, I get the clipped sine (red) as you do, but based on the manual pg 10 I would expect gate high (yellow) whenever red trace is greater than 0 (as below)? Instead it reminds me of the window comparator patch. (_traces slightly offset for clarity_)
> 
> ![image](https://private-user-images.githubusercontent.com/915048/348619244-5ca2bc21-4be0-429c-b5fb-e41fc879b042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjc3MzIsIm5iZiI6MTcyMTAyNzQzMiwicGF0aCI6Ii85MTUwNDgvMzQ4NjE5MjQ0LTVjYTJiYzIxLTRiZTAtNDI5Yy1iNWZiLWU0MWZjODc5YjA0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNzEwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTU1NjkzMzcwMWJlNjE1ZGU0NWM0ZTA1MDhiYWNkNTE1MjFkYmM0OTY4OThhMzgxYmVjMGU2YzQ0MDU5ODhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4xfE-g_CRN-qm6zEN4xTMg5Tk1puUoca_YE1_P-f-ek)

I think the confusion arises because you're interpreting the gate output (yellow) as a comparator that switches high or low based on a threshold, whereas it should be seen as an XOR output, highlighting the difference between the two signals. In the example, the gate is LOW only when the sine wave equal the voltage as the negative DC. The width of this LOW state is influenced by the margin induced by the comparator's threshold.

**Comment by BlackNoiseModular** [comment]
> @BlackNoiseModular - you might have already seen, but I have build-on-push set up here https://github.com/BlackNoiseModular/VCV/releases. If you add to the plugins folder your user folder in Rack you should be able to try it out as we go. I'm on M1 mac so use the BlackNoiseModular-2.0.0-mac-arm64.vcvplugin file (this gets auto-extracted on startup).
> 
> Still plenty to do for all modules, but it'd be good if you can take a look at the logic outputs and their gate equivelents of COSMOS, and tell me if that is what you expect? Lower hemisphere outputs are literal inverses of top hemisphere, and all gate outs should follow the truth table on pg 15 of the manual. Triggers should coincide with rising edge of all matching gate outputs.
> 
> ![image](https://private-user-images.githubusercontent.com/915048/348453233-6475851f-b98b-406f-bf0c-276b0f9bb580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjcwMjYsIm5iZiI6MTcyMTAyNjcyNiwicGF0aCI6Ii85MTUwNDgvMzQ4NDUzMjMzLTY0NzU4NTFmLWI5OGItNDA2Zi1iZjBjLTI3NmIwZjliYjU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNjU4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmI5MjYyNmI2OWJhZWM4MDE2ZDNkNzU3ODQ2YmVjZjEwZTZjMmY5YTE0YjNlNjc5MWJmODYyYTJmYmJmZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l9_xFixjsqdaVykUorbrxHNgxTm4AfTmX7NyfUbMpz0)
> 
> Once you're happy with functional behaviour, I can implement oversampling etc. :)

I tried installing it on Win11 but it doesn't work; however, it works on my old Intel Mac. My old Mac is dying, but I'll use it to tests the modules.

**Comment by hemmer** [comment]
> > @BlackNoiseModular - you might have already seen, but I have build-on-push set up here https://github.com/BlackNoiseModular/VCV/releases. If you add to the plugins folder your user folder in Rack you should be able to try it out as we go. I'm on M1 mac so use the BlackNoiseModular-2.0.0-mac-arm64.vcvplugin file (this gets auto-extracted on startup).
> > Still plenty to do for all modules, but it'd be good if you can take a look at the logic outputs and their gate equivelents of COSMOS, and tell me if that is what you expect? Lower hemisphere outputs are literal inverses of top hemisphere, and all gate outs should follow the truth table on pg 15 of the manual. Triggers should coincide with rising edge of all matching gate outputs.
> > ![image](https://private-user-images.githubusercontent.com/915048/348453233-6475851f-b98b-406f-bf0c-276b0f9bb580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjcwMjYsIm5iZiI6MTcyMTAyNjcyNiwicGF0aCI6Ii85MTUwNDgvMzQ4NDUzMjMzLTY0NzU4NTFmLWI5OGItNDA2Zi1iZjBjLTI3NmIwZjliYjU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNjU4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmI5MjYyNmI2OWJhZWM4MDE2ZDNkNzU3ODQ2YmVjZjEwZTZjMmY5YTE0YjNlNjc5MWJmODYyYTJmYmJmZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l9_xFixjsqdaVykUorbrxHNgxTm4AfTmX7NyfUbMpz0)
> > Once you're happy with functional behaviour, I can implement oversampling etc. :)
> 
> I tried installing it on Win11 but it doesn't work; however, it works on my old Intel Mac. My old Mac is dying, but I'll use it to tests the modules.

I just checked on my VM and it works. If you find user folder (Help -> Open User folder) and put it in the `plugins` dir then it should extract on open. If not could you share the log.txt in the Rack2 user folder and I can diagnose?


![Screenshot 2024-07-15 085412](https://github.com/user-attachments/assets/7afcf0f1-410c-4cae-a3bf-c6ad853f944e)
![Screenshot 2024-07-15 085547](https://github.com/user-attachments/assets/cd50b2a0-8d84-411a-a4e0-9d3cc17223db)

**Comment by BlackNoiseModular** [comment]
I started testing the modules, and I noticed that for the Slew/LFO module, the curve knob is inverted.

**Comment by hemmer** [comment]
> > ![Screenshot 2024-07-15 at 07 45 01](https://private-user-images.githubusercontent.com/915048/348617786-97a1b6d9-47b0-4fe0-8ba9-4880ca68309b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjc3MzIsIm5iZiI6MTcyMTAyNzQzMiwicGF0aCI6Ii85MTUwNDgvMzQ4NjE3Nzg2LTk3YTFiNmQ5LTQ3YjAtNGZlMC04YmE5LTQ4ODBjYTY4MzA5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNzEwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDY0NDUwMTU3YzM2MmVjNzE0NThkMGNhNTNmYzNmZjY4Y2Y5NDE4YmJhNzFkNmRiYjBiMzhjZGNmMzg5NDA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6r-8-XQu_2F_aL4JNVO0XcNGnYYPkM6wWCctAHA45PE)
> > > I took a photo to show the behavior of the "analog XOR" output and the "logic XOR" output. The green sine wave goes into the X input, and the blue DC voltage goes into the Y input. At the "analog XOR" output, the DC signal clips the sine wave (in red), but the "logic XOR" (in yellow) output works in a "bipolar" manner
> > 
> > 
> > I have to admit I'm a bit confused by this example you shared though? Sine to X, negative DC to Y, I get the clipped sine (red) as you do, but based on the manual pg 10 I would expect gate high (yellow) whenever red trace is greater than 0 (as below)? Instead it reminds me of the window comparator patch. (_traces slightly offset for clarity_)
> > ![image](https://private-user-images.githubusercontent.com/915048/348619244-5ca2bc21-4be0-429c-b5fb-e41fc879b042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjc3MzIsIm5iZiI6MTcyMTAyNzQzMiwicGF0aCI6Ii85MTUwNDgvMzQ4NjE5MjQ0LTVjYTJiYzIxLTRiZTAtNDI5Yy1iNWZiLWU0MWZjODc5YjA0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNzEwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTU1NjkzMzcwMWJlNjE1ZGU0NWM0ZTA1MDhiYWNkNTE1MjFkYmM0OTY4OThhMzgxYmVjMGU2YzQ0MDU5ODhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4xfE-g_CRN-qm6zEN4xTMg5Tk1puUoca_YE1_P-f-ek)
> 
> I think the confusion arises because you're interpreting the gate output (yellow) as a comparator that switches high or low based on a threshold, whereas it should be seen as an XOR output, highlighting the difference between the two signals. In the example, the gate is LOW only when the sine wave equal the voltage as the negative DC. The width of this LOW state is influenced by the margin induced by the comparator's threshold.

Ah OK i will try to proceed on that understanding, will take a look tonight. Sorry it's probably a bit fustrating for you conveying behaviour over text. If it looks like it's too hard to work in this model, we can loan/ship the unit and I can probe with oscilloscope instead.

**Comment by BlackNoiseModular** [comment]
> > > @BlackNoiseModular - you might have already seen, but I have build-on-push set up here https://github.com/BlackNoiseModular/VCV/releases. If you add to the plugins folder your user folder in Rack you should be able to try it out as we go. I'm on M1 mac so use the BlackNoiseModular-2.0.0-mac-arm64.vcvplugin file (this gets auto-extracted on startup).
> > > Still plenty to do for all modules, but it'd be good if you can take a look at the logic outputs and their gate equivelents of COSMOS, and tell me if that is what you expect? Lower hemisphere outputs are literal inverses of top hemisphere, and all gate outs should follow the truth table on pg 15 of the manual. Triggers should coincide with rising edge of all matching gate outputs.
> > > ![image](https://private-user-images.githubusercontent.com/915048/348453233-6475851f-b98b-406f-bf0c-276b0f9bb580.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMjcwMjYsIm5iZiI6MTcyMTAyNjcyNiwicGF0aCI6Ii85MTUwNDgvMzQ4NDUzMjMzLTY0NzU4NTFmLWI5OGItNDA2Zi1iZjBjLTI3NmIwZjliYjU4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNjU4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MmI5MjYyNmI2OWJhZWM4MDE2ZDNkNzU3ODQ2YmVjZjEwZTZjMmY5YTE0YjNlNjc5MWJmODYyYTJmYmJmZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l9_xFixjsqdaVykUorbrxHNgxTm4AfTmX7NyfUbMpz0)
> > > Once you're happy with functional behaviour, I can implement oversampling etc. :)
> > 
> > 
> > I tried installing it on Win11 but it doesn't work; however, it works on my old Intel Mac. My old Mac is dying, but I'll use it to tests the modules.
> 
> I just checked on my VM and it works. If you find user folder (Help -> Open User folder) and put it in the `plugins` dir then it should extract on open. If not could you share the log.txt in the Rack2 user folder and I can diagnose?
> 
> ![Screenshot 2024-07-15 085412](https://private-user-images.githubusercontent.com/915048/348634163-7afcf0f1-410c-4cae-a3bf-c6ad853f944e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzA1ODMsIm5iZiI6MTcyMTAzMDI4MywicGF0aCI6Ii85MTUwNDgvMzQ4NjM0MTYzLTdhZmNmMGYxLTQxMGMtNGNhZS1hM2JmLWM2YWQ4NTNmOTQ0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNzU4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDhkNjM5NzkyYjY0YTQxMzQwNWZjZmVhZDg3YmZlY2M5ZWQyNDkzODNjYzE5NTAyYWZlY2ZmMDhlN2MwZGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P6a1zxfscg9DMpNMc9qQqm325Vt6NtXeQjsxgbITG6E) ![Screenshot 2024-07-15 085547](https://private-user-images.githubusercontent.com/915048/348634171-cd50b2a0-8d84-411a-a4e0-9d3cc17223db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzA1ODMsIm5iZiI6MTcyMTAzMDI4MywicGF0aCI6Ii85MTUwNDgvMzQ4NjM0MTcxLWNkNTBiMmEwLThkODQtNDExYS1hNGUwLTlkM2NjMTcyMjNkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNzU4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZGE0YzNlMmY3OTQ5MGU1NDZkZWZhZmVjY2U4OTYzMTVlNWQ5YTMzYmRjZDk1MGRmMTMxNWFjNzBiOWJmYjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yc0kuxe3kUeJsX2Z00MlkLTt8r7FxklvucG1XDHf_Jg)

I tried as you instructed, opening the file from VCV instead of directly from the folder, and now it works! ;)

**Comment by BlackNoiseModular** [comment]
No problem, I can send you the hardware modules. I think that will answer your questions more quickly and clearly than my explanations, haha. And if you don't want to keep them, you can return them once the modules are available on VCV. If that works for you, just give me an address, and I'll take care of the rest ;)

**Comment by hemmer** [comment]
Hardware version has arrived, and up and running testing / comparing  🎉 

![image](https://github.com/user-attachments/assets/24c60e10-e78a-464e-a7f0-4e574b142317)

**Comment by hemmer** [comment]
Notes (just for my benefit):


* I think I'm starting to get the XOR gate output now after a bit of experimentation. When the two signals are the "same", gate out is zero otherwise high. In this case "same" is assessed with Schmitt trigger so "first equal then + 0.5V of tolerance", where this has the usual hysteresis of Schmitt triggers, so in example below from hardware (rising sine) it's +0.5V and falling sine it's -0.5V. 😅 

![image](https://github.com/user-attachments/assets/333a4316-3753-46e4-8e9d-1faafb3b9f61)



* for OR (and similar outputs), gate out high at a threshold of about 0.5V, same for falling as rising, i.e. no hysteresis (maybe make this threshold menu configurable), hardware scope example below

![image](https://github.com/user-attachments/assets/b0bb2ac7-c9a4-41d5-a659-9f693798cbd8)

**Comment by hemmer** [comment]
First pass at oversampling for various outputs, example is full rectifier. Lots of aliasing (especially with gates) at high frequencies, which is strongly mitigated with oversampling. 

![image](https://github.com/user-attachments/assets/6b86123d-32c4-4061-81bb-9eefaa9d9438)

**Comment by hemmer** [comment]
Touch pad now outputs voltage (configurable from menu) that is proportional from how close to the centre of the pad you are.

**Comment by hemmer** [comment]
@BlackNoiseModular - I'm probably now reaching the point with COSMOS where it's worth you taking a look to see if you are happy. Still TODO are update to production graphics, and maybe tweaks/experimentation with the pressure pads. Same for GOMA II. 

As for SlewLFO I'm still working on it, so if you want to wait until all ready for reivew then that's fine (note I have a couple of questions there, again no rush).
