### ISSUE TITLE
BlackNoiseModular v2.0.0 release

### ISSUE THREAD

**Issue by hemmer** [BlackNoiseModular/VCV#4]
Modules

- [x] #1  
- [x] #2 
- [x] #3

General
- [x] Automatic builds
- [x] Confirm license (GPLv3)
- [x] Confirm graphics/copyright license
- [x] Check user manual examples can be reproduced
- [x] Manufacturer testing
- [x] User testing
- [x] Submit to library 🎉

**Comment by hemmer** [comment]
@BlackNoiseModular - can you confirm if you are happy with GPL-v3-or-later license? It is default reccomended for VCV open source projects, and means we can re-use other GPL-v3-or-later code with ease?

**Comment by BlackNoiseModular** [comment]
> @BlackNoiseModular - can you confirm if you are happy with GPL-v3-or-later license? It is default reccomended for VCV open source projects, and means we can re-use other GPL-v3-or-later code with ease?

I’m not an expert on licenses, but it seems like releasing the modules under a "freeware" license might be the best solution.

**Comment by hemmer** [comment]
> > @BlackNoiseModular - can you confirm if you are happy with GPL-v3-or-later license? It is default reccomended for VCV open source projects, and means we can re-use other GPL-v3-or-later code with ease?
> 
> I’m not an expert on licenses, but it seems like releasing the modules under a "freeware" license might be the best solution.

It depends on philosophy, and what you want the project to be etc. Do you want it to be open source? Advantages are that people can contribute fixes, we can use other open source code (gpl'ed), it can be used in other related projects (e.g. cardinal). Sometimes if there is commercially sensitive code (eg DSP code that runs on the hardware) you might want closed source. 

Certainly all the projects I've been involved so far (Befaco, Rebel Tech, Bastl) have been open source and benefited from it. If you do decide for open source, I'd advocate for gpl-v3-or-later license.

But of course totally up to you and I'm happy to go with your decision, no pressure.

The reason I'm asking now is that the oversampling code I was intending to use I've developed under GPL so we'd need to use another solution for that part instead if you don't want to go open source (which again is fine).

Freeware VCV license is closed source btw in case that's not clear

**Comment by hemmer** [comment]
Another example (and then I'll be quiet 😅 ) - we can't re-use the Slew code from Befaco unless we're also open source, GPL-v3-or-later. Not the end of the world, but would need re-implemented.

**Comment by BlackNoiseModular** [comment]
I discussed about it with Pierre, who knows much more about licenses and their use in VCV than I do, and at the end, I think the GPL-V3 license is the best solution.

However, he raised an interesting question regarding the graphics of the modules, the module names, and essentially everything that constitutes the identity of Black Noise and its modules : 

_-Is it possible to release under the GPL-V3 license while retaining exclusive use of the elements that define the identity of these modules and the Black Noise brand?_

**Comment by hemmer** [comment]
> I discussed about it with Pierre, who knows much more about licenses and their use in VCV than I do, and at the end, I think the GPL-V3 license is the best solution.

Ok great, thanks for confirming.


> However, he raised an interesting question regarding the graphics of the modules, the module names, and essentially everything that constitutes the identity of Black Noise and its modules :
> 
> _-Is it possible to release under the GPL-V3 license while retaining exclusive use of the elements that define the identity of these modules and the Black Noise brand?_

And yes good question - there is a good setup for VCV fundemental modules I think (see [here](https://github.com/VCVRack/Fundamental/blob/v2/LICENSE.md)). Essentially the brand, logo are copyrighted, and graphics licensed seperately under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/), which stops people selling copies or tweaking the design etc etc. We could definitely add something similar would that cover it?

It's maybe hard to cover what "defines the identity" of the modules completely, and even without this VCV plugin there's nothing stopping someone going to modulargrid, looking at the module description and making something similar. If there are specific concerns that aren't covered by the above let me know, otherwise we can proceed on this basis.

**Comment by hemmer** [comment]
submitted to library: https://github.com/VCVRack/library/issues/815
